### ISSUE TITLE
Validate button only for mappers who clicked previously on Edit with JOSM

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-tasking-manager2#598] opened 2015-05-09 11:22 UTC
As JOSM is really more powerful for data quality check and correction (Validator + displaying the data at medium scale for overview glance that is important eg for road network checking), I suggest that the Validate button only for mappers who clicked previously on Edit with JOSM

**Comment by pierzen** [comment] 2015-05-09 12:15
One easy implementatioln would be to look at date of OSM account creation. Let's say, if you have less then a month of experience with OSM, the button do not show.

**Comment by mataharimhairi** [comment] 2015-05-09 15:49
Is time the best indicator though? They may have had an OSM account for a year or so, but not been very active, which would mean they're not that experienced. A way to extract the amount of previous validations they've completed would be better, but probably not as easy to implement.

**Comment by pierzen** [comment] 2015-05-09 16:23
The no of changesets could surely better show the progression of a contributor. Not perfect since some have a changeset per building. But a stat we could use.

The OSM API provides the no. of changesets.
http://www.openstreetmap.org/api/0.6/user/osm uid no.

**Comment by danbjoseph** [comment] 2015-06-02 14:57
Given the diversity of mappers (e.g. a GIS expert could have just joined and have the skills/experience to validate in a very short time) and of task difficulty (level of detail requested, quality of imagery, etc.), I think it would be difficulty to automate validator status of contributors using metrics/stats. I would like to see an option for validator roles on tasks. Perhaps making it default that the task creator needs to add approved osm users to a validators list, with the option to turn on open validation by any user. There could possibly be a master list of HOT approved validators that can be turned on for a task (in addition to the creator approving additional validators for just that task).

**Comment by pgiraud** [comment] 2015-06-03 06:06
+1 @danbjoseph I like this idea too. And I can confirm that it's technically feasible.

**Comment by pgiraud** [comment] 2015-07-29 07:45
I think we agree on the fact that it's difficult to automate the acquisition of validation privileges.
And relying on users' preferred editor is really not a good option.
Closing.

See #587 as well.

**Closed by pgiraud** 2015-07-29 07:45 UTC
Labels: UI, validation
