### ISSUE TITLE
Tiles not loading on projects

### ISSUE THREAD

**Issue by d3netxer** [hotosm/osm-tasking-manager2#701] opened 2015-11-16 06:32 UTC
Anybody else not seeing the basemap load on projects? I think because the requested tiles are being requested with a https (https://b.tile.openstreetmap.fr/hot/10/564/511.png), if the tiles were requested with http, I think they would show up fine.

**Comment by dodobas** [comment] 2015-11-16 08:17
HTTPS support is still 'experimental', the TM2 service does not have any issues with https, but we do depend on external tile services hosted by osm.fr which show somewhat unreliable https support. It's hard to figure out why it occurred, as it only sometimes manifests it self as a self-signed certificate. For me, the requested tile loads just fine in firefox, chromium and midori browser, at the moment.

There is nothing on the server that forces you to use https, however your browser might have 'remembered' you once used it, and now redirects to https by default. Also, there are some browser plugins that will force https usage.

**Comment by cgiovando** [comment] 2015-11-16 21:18
Same problem here, as already mentioned on the AWG list, background map is not loading because of browser defaulting to httpS. Tried with Chrome and Safari, cleaned up the cache for hotosm.org, disabled all extensions, and even incognito session, still goes to httpS and no tiles.

Can we revert tasks.hotosm.org temporarily to use HTTP until the problem is fixed on openstreetmap.fr?

Alternatively, can we use tiles from another service (e.g. Mapbox)?

It doesn't look like I can assign labels, but to me this issue should be "priority_high".

Thanks @pgiraud and @dodobas

**Comment by skorasaurus** [comment] 2015-11-19 18:37
Before we look for a new provider, have we asked anyone at openstreetmap.fr if they're aware of a problem with HTTPS and if so, their timeline for fixing it? 

ping @cquest (on the OSM-FR technical team)

**Comment by cquest** [comment] 2015-11-19 19:51
I've checked and https://b.tile.openstreetmap.fr/hot/10/564/511.png loads correctly for me but Firefox complains about the certificate.
Our tile server has been reconfigured recently on the http side by adding nginx in front with some cache enabled, but it does not seem to be related as https is still served by apache/mod_tile

**Comment by cquest** [comment] 2015-11-19 20:04
I've check the certificate... it comes from http://www.CAcert.org.
It looks like Firefox does not recognize it because of MD5 hashing (https://wiki.cacert.org/FAQ/BrowserClients#Mozilla_Firefox)
I'll check if we can switch to another certificate provider to avoid these problems.

**Comment by cgiovando** [comment] 2015-11-23 02:38
@dodobas - may HOT be able to help through our cert provider?

Or else does Cloudfare offer a free solution? https://www.cloudflare.com/ssl/

**Comment by d3netxer** [comment] 2015-11-23 04:29
I suggest moving temporarily to a Tile Provider that shows reliable https support

**Comment by cquest** [comment] 2015-11-23 08:00
We've updated the tile server setup to reuse our wildcard certificate.

Instead of a/b/c.tile.openstreetmap.fr you can switch to tile-a/b/c.openstreetmap.fr
Example: https://tile-a.openstreetmap.fr/osmfr/6/32/22.png

**Comment by cquest** [comment] 2015-11-23 08:03
Bonus: we've also switched from apache to nginx to serve tiles with https and use the same tile cache for http and https. Map loading should now be faster.

**Comment by d3netxer** [comment] 2015-11-26 22:22
That is good news @cquest . Does that mean someone now needs to change the url pattern for tiles in the project.js file and make a commit?

**Comment by d3netxer** [comment] 2015-12-04 02:42
I see your commit @cquest that alters the url pattern and the following commit that makes the pattern fit the relative pattern. In my browser now the tiles are still coming in the old format. Do the changes still need to push live?

**Comment by d3netxer** [comment] 2016-02-02 01:55
Can we get the tile.openstreetmap.fr certificate corrected or switch to another set of tiles? This issue has not been resolved yet. I am getting errors with this certificate with Chrome, Firefox, Safari, https://cryptoreport.websecurity.symantec.com/checker/views/certCheck.jsp, and https://www.sslshopper.com/ssl-checker.html#hostname=https://c.tile.openstreetmap.fr/hot/12/1132/2107.png.

![screen shot 2016-02-01 at 8 40 06 pm](https://cloud.githubusercontent.com/assets/2665840/12737397/0d1dc1c4-c926-11e5-8a92-b53a9233371c.png)

**Comment by stefanb** [comment] 2016-06-12 07:41
This seems to have been fixed by migrating to Let's Encrypt CA.

**Comment by bgirardot** [comment] 2016-11-22 09:16
Between osm.fr making changes and hot backing out https, this issue seems resolved, please reopen it if not. thank you to everyone for helping get it figured out.

**Closed by bgirardot** 2016-11-22 09:16 UTC

**Comment by answerquest** [comment] 2017-10-29 17:45
Alert : As of 29 Oct'17, Tiles not loading again for western India, beyond 50km scale zoom (ie anything deeper than country-view) Here are a couple of error'd URLs:
http://tile-a.openstreetmap.fr/hot/8/180/114.png 
http://tile-c.openstreetmap.fr/hot/8/179/114.png

Requesting a feature to allow the task's admin to change the tile source.
Default OSM tiles should be fine:
`http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`

**Comment by cquest** [comment] 2017-10-30 08:00
Sorry for the tileserver outage.
I'm working on getting it back online...

Some tiles are still available as they are in our tile cache.
