### ISSUE TITLE
Automatic changesets names do not look good in the OSM history

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-tasking-manager2#549] opened 2015-02-14 22:33 UTC
Eg http://www.openstreetmap.org/user/florisnijhuis/history with changesets like this:

%23CARCrisis%2C%20CAR%2C%20Rafai%2C%20%23MapGive%2C%20%23hotosm-project-883%20%2F%20source%3DWorldView-1%2C%20DigitalGlobe%2C%20NextView%2C%20March%2024%2C%202014

**Comment by pgiraud** [comment] 2015-02-15 08:53
Already reported. Duplicate of https://github.com/hotosm/osm-tasking-manager2/issues/513

**Closed by pgiraud** 2015-02-15 08:53 UTC
